@startuml reto 2
  start
    :s = str(7)|
    :range_limit = int(s+s)|

    partition square_array{
      repeat
        :i = i**2|
      repeat while (i in array) is (yes)
    }

    partition ascending_order_array{
      repeat
        repeat
          if (array[i] > array[j]) then (yes)
            :array[i], array[j] = array[j], array[i];
          endif
        repeat while (j in range(i+1, len(array))) is (yes)
      repeat while (i in range(len(array))) is (yes)
    }

    partition modify_list_in_place{
      :aux_array = []|
      repeat
        if (i < range_limit and i >= 0) then (yes)
          :aux_array.append(i)|
        endif
      repeat while (i in array) is (yes)
    }

    :array = [1, 2, 3, 4, 5, 7]|
  
    :array = square_array(array)|
    :array = ascending_order_array(array)|
    :array = modify_list_in_place(array)|
  end
@enduml