@startuml reto 2
  start
    :s = str(7)|
    :range_limit = int(s+s)|

    partition square_array{
    }

    partition ascending_order_array{
    }

    partition modify_list_in_place{
    }

    :array = [1, 2, 3, 4, 5, 7]|
    if (len(array) >= 100) then (yes)
      :array = square_array(array)|
      :array = ascending_order_array(array)|
      :array = modify_list_in_place(array)|
  end
@enduml