@startuml
start
  partition modify_list_in_place {
  :write_index = 0|

  repeat
    :new_num_str = ''|
    note left 
      Almacenamos el nuevo número como 
      cadena para preservar ceros a la 
      izquierda
    end note
    repeat
      :digit = int(digit_str)|
      if (digit < s) then (yes)
        :new_num_str += digit_str ]
      endif
    repeatwhile (digit_str in str(num))

    if (new_num_str) then (yes)
      note left
        Si la cadena no está 
        vacia convertimos 
        a entero y lo agregamos
      end note
      :data[write_index] = int(new_num_str) ]
      :write_index += 1 ]
    endif
  repeatwhile (num in data)

  : del data[write_index:] ]
  note right
    Elimina todos los elementos 
    en la lista data
    desde write_index
  end note
  }
end
@enduml